package com.ribbontek.slsrouter.util

// Retrieved status codes from io.grpc.Status.Code
const val OK_STATUS_CODE = 0
const val CANCELLED_STATUS_CODE = 1
const val UNKNOWN_STATUS_CODE = 2
const val INVALID_ARGUMENT_STATUS_CODE = 3
const val DEADLINE_EXCEEDED_STATUS_CODE = 4
const val NOT_FOUND_STATUS_CODE = 5
const val ALREADY_EXISTS_STATUS_CODE = 6
const val PERMISSION_DENIED_STATUS_CODE = 7
const val RESOURCE_EXHAUSTED_STATUS_CODE = 8
const val FAILED_PRECONDITION_STATUS_CODE = 9
const val ABORTED_STATUS_CODE = 10
const val OUT_OF_RANGE_STATUS_CODE = 11
const val UNIMPLEMENTED_STATUS_CODE = 12
const val INTERNAL_STATUS_CODE = 13
const val UNAVAILABLE_STATUS_CODE = 14
const val DATA_LOSS_STATUS_CODE = 15
const val UNAUTHENTICATED_STATUS_CODE = 16

// OK(0),
// CANCELLED(1),
// UNKNOWN(2),
// INVALID_ARGUMENT(3),
// DEADLINE_EXCEEDED(4),
// NOT_FOUND(5),
// ALREADY_EXISTS(6),
// PERMISSION_DENIED(7),
// RESOURCE_EXHAUSTED(8),
// FAILED_PRECONDITION(9),
// ABORTED(10),
// OUT_OF_RANGE(11),
// UNIMPLEMENTED(12),
// INTERNAL(13),
// UNAVAILABLE(14),
// DATA_LOSS(15),
// UNAUTHENTICATED(16);
